"""
Phase 2: Building the Adjacency Matrix (The Spatial Map)
Transforms GPS Coordinates into a mathematically rigorous Sparse Graph.
"""
import pandas as pd
import numpy as np
import math

def haversine(lat1, lon1, lat2, lon2):
    """Calculates the physical distance (in kilometers) between two GPS points."""
    R = 6371.0 # Earth radius in kilometers
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat/2)**2 + 
         math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon/2)**2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

def create_adjacency_matrix():
    print("1. Loading physical intersection GPS data...")
    # Load the clean file generated by data_processor.py
    df = pd.read_csv('GeneratedFiles/cleaned_scats_directional_data.csv')

    # Extract the 140 unique nodes and their GPS coordinates
    nodes_df = df[['Node_ID', 'SCATS Number', 'NB_LATITUDE', 'NB_LONGITUDE']].drop_duplicates()
    nodes_df = nodes_df.sort_values('Node_ID').reset_index(drop=True)

    num_nodes = len(nodes_df)
    print(f"-> Found {num_nodes} unique nodes.")

    # Create an empty 140x140 grid filled with zeros
    adj_matrix = np.zeros((num_nodes, num_nodes))

    # --- HYPERPARAMETERS ---
    sigma = 1.0           # Controls how fast the connection weight drops off
    threshold_km = 2.0    # THE FIX: Maximum distance for two nodes to be considered "connected"

    print(f"2. Calculating spatial connections (Cutoff Threshold: {threshold_km}km)...")
    
    connections_made = 0
    for i in range(num_nodes):
        lat1 = nodes_df.loc[i, 'NB_LATITUDE']
        lon1 = nodes_df.loc[i, 'NB_LONGITUDE']

        for j in range(num_nodes):
            if i == j:
                adj_matrix[i, j] = 1.0 # A node is perfectly connected to itself
                connections_made += 1
            else:
                lat2 = nodes_df.loc[j, 'NB_LATITUDE']
                lon2 = nodes_df.loc[j, 'NB_LONGITUDE']
                dist_km = haversine(lat1, lon1, lat2, lon2)

                # --- THE FIX: SPARSITY ---
                # If nodes are further than 2km apart, they have 0 connection.
                if dist_km <= threshold_km:
                    # Apply Gaussian kernel to turn physical distance into a 0.0-1.0 weight
                    weight = np.exp(-(dist_km**2) / (sigma**2))
                    adj_matrix[i, j] = weight
                    connections_made += 1

    # Calculate sparsity percentage for the report
    total_possible = num_nodes * num_nodes
    sparsity = ((total_possible - connections_made) / total_possible) * 100
    
    print(f"-> Map generated. Matrix is {sparsity:.2f}% sparse (0.0 weights).")

    # Save the files for the Neural Network to use
    np.save('GeneratedFiles/adjacency_matrix.npy', adj_matrix)
    nodes_df.to_csv('GeneratedFiles/node_lookup_table.csv', index=False)
    
    print("\n--- MATRIX BUILT SUCCESSFULLY ---")
    print("Saved 'adjacency_matrix.npy' and 'node_lookup_table.csv' to GeneratedFiles/")

if __name__ == "__main__":
    create_adjacency_matrix()